namespace: liferaynetes
bases:
 - ./../base
 - ./../../components/nfs-hostpath
 - ./../../components/ingress-nginx
 - ./../../components/postgres
 - ./../../components/elasticsearch-single

patchesStrategicMerge:
- patches/liferay-web.yaml
- patches/ingress.yaml

resources:
 - namespace.yaml
 - shell.yaml
