version: "2.1"

services:
  liferay:
    build: components/liferay
    image: mattipaksula/liferay
    ports:
      - 8080:8080
    links:
      - postgres
      - elasticsearch
    volumes:
      - ./deploy:/app/deploy
      - ./nfs/document_library:/app/data/document_library
  fuploads:
    image: mattipaksula/fuploads
    volumes:
      - ./deploy:/usr/src/app/uploads
    ports:
      - 8081:8080
  postgres:
    image: postgres:9.6-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=liferay
      - POSTGRES_PASSWORD=liferay
      - POSTGRES_DB=liferay
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster

volumes:
  postgres-data:
