apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: liferay
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mattipaksula/liferaynetes
        volumeMounts:
          - name:  document-library
            mountPath: /app/data/document_library
        env:
          - name: STARTUP_DELAY_MULTIPLIER
            value: "15"
          - name: MAX_RAM_PERCENTAGE
            value: "25"
          - name: MEMORY_LIMIT_BYTES
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
      volumes:
        - name: document-library
          persistentVolumeClaim:
            claimName: document-library
