apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        env:
          - name: POSTGRES_USER
            value: liferay
          - name: POSTGRES_PASSWORD
            value: liferay
          - name: POSTGRES_DB
            value: liferay
        resources:
          requests:
            memory: "128M"
            cpu: "0.1"
          limits:
            memory: "1024M"
            cpu: "8.0"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
