---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-volume
  namespace: liferaynetes
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim
  namespace: liferaynetes
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi