apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
          limits:
            memory: "3Gi"
            cpu: "8"
