
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: exoliferayde@mattipaksula.com
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  commonName: exoliferay.de
  dnsNames:
  - exoliferay.de
  - "www.exoliferay.de"
  - "0.exoliferay.de"
  - "1.exoliferay.de"
  - "2.exoliferay.de"
  - "3.exoliferay.de"
  - "4.exoliferay.de"
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - exoliferay.de
      - "www.exoliferay.de"
      - "0.exoliferay.de"
      - "1.exoliferay.de"
      - "2.exoliferay.de"
      - "3.exoliferay.de"
      - "4.exoliferay.de"
